site_name: FutureProofHomes Docs
site_url: https://docs.futureproofhomes.net
repo_url: https://github.com/FutureProofHomes/Documentation
theme:
  logo: assets/square_transparent_black_logo_vector_300x300.svg
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - header.autohide
    - toc.integrate
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: custom
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: custom
extra_css:
  - stylesheets/extra.css
extra:
  social:
    # - icon: fontawesome/icon/home
    #   link: https://futureproofhomes.net
    - icon: fontawesome/brands/github-alt
      link: https://github.com/FutureProofHomes
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@futureproofhomes
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/AIVoiceAssist
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/futureproofhome

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


extra_javascript:
  # - javascript/installer.js
  - javascript/esp-web-tools/install-button.js
  # - https://cdn.jsdelivr.net/npm/esp-web-tools@10/dist/web/install-button.js?module

copyright: |
  &copy; 2024 <a href="https://futureproofhomes.net" target="_blank" rel="noopener">FutureProof Homes LLC</a>
