site_name: FutureProofHomes Docs
site_url: https://docs.futureproofhomes.net
repo_url: https://github.com/FutureProofHomes/Documentation

nav:
  - Welcome: index.md
  - Satellite1 Dev Kit:
    - Introduction: satellite1-introduction.md
    - Getting Started:
      - Recommended Accessories: satellite1-recommended-accessories.md
      - CORE & HAT Assembly: satellite1-assembly.md
      - Connect to Home Assistant: satellite1-connecting-to-ha.md
      - Adding Presence Sensors: satellite1-presence-sensors.md
    - Home Assistant Configuration:
      - Set Up Voice Control: satellite1-set-up-voice-control.md
      - Streaming Music: satellite1-streaming-music.md
      - Awesome Automations: satellite1-awesome-automations.md
    - Flashing Firmware: 
      - Flash via USB-C Cable: satellite1-flash-via-usb-c.md
      - Modifying the Firmware: satellite1-modifying-the-firmware.md
    - Support:
      - Troubleshooting: satellite1-troubleshooting.md
      - FAQs: satellite1-faqs.md
  - Expansion Modules:
    - PoE "SHOE" Module: satellite1-poe-shoe-module-overview.md
    - Amplifier1 Module: satellite1-amplifier-module-overview.md
  - Enclosures & Mount Kits:
    - Cylindrical Enclosure: satellite1-dev-kit-enclosure.md
    - In-Ceiling Mount Kit: satellite1-mount-kit-overview.md
  - AI Base Station:
    - Introduction: ai-base-station-introduction.md


theme:
  logo: assets/square_transparent_black_logo_vector_300x300.svg
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.expand
    - navigation.tracking
    - navigation.prune
    
    # - toc.integrate
    
    - search.suggest
    - search.highlight
    # - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: custom
      accent: custom
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: custom
      accent: custom
extra_css:
  - stylesheets/extra.css
  - stylesheets/firmware_selector.css
extra:
  social:
    # - icon: fontawesome/icon/home
    #   link: https://futureproofhomes.net
    - icon: fontawesome/brands/github-alt
      link: https://github.com/FutureProofHomes
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@futureproofhomes
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/AIVoiceAssist
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/futureproofhome

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  # - optimize
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  # - redirects:
  #     redirect_maps:
  #       'old.md': 'new.md'
  #       'old/file.md': 'new/file.md'
  #       'some_file.md': 'http://external.url.com/foobar'

extra_javascript:
  # - javascript/installer.js
  - javascript/esp-web-tools/install-button.js
  # - https://cdn.jsdelivr.net/npm/esp-web-tools@10/dist/web/install-button.js?module
  - javascript/keyboard_shortcuts_fix.js
  - javascript/firmware_selector.js
  
copyright: |
  &copy; 2024 <a href="https://futureproofhomes.net" target="_blank" rel="noopener">FutureProofHomes, Inc</a>