site_name: FutureProofHomes Docs
site_url: https://docs.futureproofhomes.net
repo_url: https://github.com/FutureProofHomes/Documentation

nav:
  - Home: index.md
  - Set Up Voice Control: set-up-voice-control.md
  - Streaming Music: streaming-music.md
  - Modifying the Firmware: modifying-the-firmware.md
  - Presence Sensors: presence-sensors.md
  - Awesome Automations: awesome-automations.md
  - Recommended Accessories: recommended-accessories.md
  - Troubleshooting: troubleshooting.md
  - FAQs: faqs.md

theme:
  logo: assets/square_transparent_black_logo_vector_300x300.svg
  name: material
  custom_dir: docs/overrides
  features:
    # - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    
    - toc.integrate
    
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: custom
      accent: custom
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: custom
      accent: custom
extra_css:
  - stylesheets/extra.css
extra:
  social:
    # - icon: fontawesome/icon/home
    #   link: https://futureproofhomes.net
    - icon: fontawesome/brands/github-alt
      link: https://github.com/FutureProofHomes
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@futureproofhomes
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/AIVoiceAssist
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/futureproofhome

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false

extra_javascript:
  # - javascript/installer.js
  - javascript/esp-web-tools/install-button.js
  # - https://cdn.jsdelivr.net/npm/esp-web-tools@10/dist/web/install-button.js?module

copyright: |
  &copy; 2024 <a href="https://futureproofhomes.net" target="_blank" rel="noopener">FutureProofHomes, Inc</a>
