name: Download and Commit Release from ESPHome Repos

on:
  workflow_dispatch:  # Allows manual trigger of the workflow
    inputs:
      esphome_release_tag:
        description: 'Tag of the ESPHome release firmware to download'
        required: true
env:
  esphome_repo: FutureProofHomes/Satellite1-ESPHome
  xmos_repo: FutureProofHomes/Satellite1-XMOS
jobs:
  download-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4

    - name: Create manifest files for each hardware revision
      run: |
        chmod +x ./scripts/create_manifest.sh
        export GITHUB_TOKEN=${{ secrets.PAT_TOKEN }}
        ./scripts/create_manifest.sh ${{ github.event.inputs.esphome_release_tag }} ${{ env.esphome_repo }}

    - name: Add and commit release assets to the current repository
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Add ESPHome Firmware: ${{ github.event.inputs.esphome_release_tag }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
